id = "ez"
name = "EZ"
description = "Support for the EZ programming language"
version = "0.1.0"
schema_version = 1
authors = ["Marshall Burns"]

[grammars.ez]
name = "EZ"
scope = "source.ez"
path = "syntaxes/ez.tmLanguage.json"

[languages.ez]
name = "EZ"
grammar = "ez"
path_suffixes = ["ez"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
